### ISSUE TITLE
Dokončan projekt

### ISSUE THREAD

**Issue by MancaStrgar** [jaanos/OPB-2016#2]
Pozdravljeni, 
prosim če lahko dodate najin projekt Brskalnik po spletnih trgovinah.
Hvala,
Manca Strgar in Klemen Hovnik

**Comment by jaanos** [comment]
Nimam večjih pripomb, tako da bom dodal povezavo, z @alenFMF pa se lahko domenita za termin zagovora, če se še nista. Edino zavihek *Nakupovalni seznam* izgleda nekoliko odveč, saj samo ponovi vpisano besedilo. Zanimivo bi bilo, če bi vpisane vrednosti povezala z artikli v bazi.

Če bosta še kaj spreminjala, mi prosim javita, da posodobim povezavo.

**Comment by HovnikK15** [comment]
Pozdravljeni, ali lahko ponovno posodobite povezavo za najin projekt. 
Hvala in lep pozdrav

**Comment by jaanos** [comment]
Bom posodobil.
