### ISSUE TITLE
Oddaja projekta

### ISSUE THREAD

**Issue by klara-stantic** [jaanos/OPB-2016#4]
Pozdravljeni, 
projekt [Gasilski pomočnik](https://github.com/klara-stantic/opb_gasilski_pomocnik) je končan. Za Binder sva dodala ustrezne datoteke, vendar javlja napako: Could not find path: proxy/8080

Lep pozdrav, 
Klara Stantič in Tine Fabiani

**Comment by jaanos** [comment]
Tole ni šlo na pravo mesto, tako da zapiram. Odprita issue na svojem repozitoriju, da vama @gasperxy lahko pokomentira in pomaga odpraviti težave.
